services:
  - type: web
    name: driver-qualification-tool
    env: node
    buildCommand: npm run build:prod
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /api/health
    autoDeploy: true
    buildFilter:
      paths:
        - server/**
        - client/**
        - shared/**
        - package.json
        - tsconfig.server.json
        - vite.config.ts
