previews:
  generation: automatic

services:
  - type: web
    runtime: node
    name: DriverQualificationTool
    repo: https://github.com/T-SaaS/DriverQualificationTool
    numInstances: 1
    region: Oregon (US West)
    plan: hobby
    branch: main
    buildCommand: npm run build:prod
    startCommand: npm start
    autoDeploy: true
    maxShutdownDelaySeconds: 120
    healthCheckPath: /api/health
    buildFilter:
      paths:
        - server/**
        - client/**
        - shared/**
        - package.json
        - tsconfig.server.json
        - vite.config.ts
        - tailwind.config.ts
        - postcss.config.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: ZEPTOMAIL_API_KEY
        sync: false
      - key: ZEPTOMAIL_API_URL
        value: api.zeptomail.com/
      - key: COMPANY_NAME
        value: TruckingMBA
      - key: ALLOWED_ORIGINS
        value: https://driverqualificationtool.onrender.com
      - fromGroup: supabase-config
      - fromGroup: email-config

envVarGroups:
  - name: supabase-config
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
  - name: email-config
    envVars:
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: ZEPTOMAIL_API_KEY
        sync: false
      - key: ZEPTOMAIL_API_URL
        value: api.zeptomail.com/
      - key: COMPANY_NAME
        value: TruckingMBA
